FROM mysql:8

ENV MYSQL_ALLOW_EMPTY_PASSWORD yes
RUN mkdir -p /mysql
COPY mysql_blog.sql /mysql
COPY privileges.sql /mysql
COPY setup.sh /docker-entrypoint-initdb.d
 
RUN chmod a+x /docker-entrypoint-initdb.d/setup.sh